- name: Generate private key
  ansible.builtin.command:
    cmd: openssl genrsa -out {{ certificate_dir }}/{{ private_key_name }} {{ default_bits }}
  args:
    creates: "{{ certificate_dir }}/{{ private_key_name }}"
  register: command_output

- name: Read private key
  ansible.builtin.slurp:
    src: "{{ certificate_dir }}/{{ private_key_name }}"
  register: private_key_content
  when: not ansible_check_mode

- name: Export private key to azure vault
  azure.azcollection.azure_rm_keyvaultsecret:
    keyvault_uri: "{{ azure_key_vault_uri }}"
    secret_name: "{{ azure_vault_private_key_name }}"
    secret_value: "{{ private_key_content.content | b64decode }}"
    state: present
    auth_source: env
  delegate_to: localhost
  # vars:
  #   ansible_python_interpreter: /home/GitHubActions/ansible-venv/bin/python
  run_once: true
  when: not ansible_check_mode
  environment:
    AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    AZURE_SECRET: "{{ lookup('env', 'AZURE_SECRET') }}"
    AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"
    AZURE_SUBSCRIPTION_ID: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"