- name: Check if ACME account exists
  ansible.builtin.stat:
    path: "{{ certbot_config_dir }}/accounts"
  register: acme_accounts
  when: not ansible_check_mode
  tags:
    - acme_register

- name: Register ACME Account
  ansible.builtin.command:
    cmd: >
      certbot register
      --agree-tos
      -m {{ acme_account_email }}
      --config-dir {{ certbot_config_dir }}
      --work-dir {{ certbot_work_dir }}
      --logs-dir {{ certbot_logs_dir }}
  when: not acme_accounts.stat.exists and not ansible_check_mode
  tags:
    - acme_register