azure_vault_private_key_name: "prometheuskey"
azure_vault_certificate_name: "prometheuscert"
azure_vault_fullchain_name: "prometheusfullchain"
azure_vault_chain_name: "prometheuschain"

private_key_name: "prometheus.key"
csr_file_name: "prometheus_csr"
csr_config_file_name: "prometheus_csr_config"
certificate_name: "prometheus_cert.pem"
chain_name: "prometheus_chain.pem"
fullchain_name: "prometheus_fullchain.pem"

CN: "prometheus.robotshopapp.in"

san_domains:
  - "prometheus.robotshopapp.in"